# Generated by Django 6.0 on 2025-12-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='team_image_alt',
        ),
    ]
