# Generated by Django 6.0 on 2025-12-11 20:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_teammember_team_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
