# Generated by Django 6.0 on 2025-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='will_be_in_hero',
            field=models.BooleanField(default=False, help_text='Check this box if you want this post to be featured in the hero section.'),
        ),
    ]
